name: 'Pull Request Lint'
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
jobs:
  title_validation:
    name: Title Format Validation for Jira
    runs-on: ubuntu-latest
    steps:
      - uses: seferov/pr-lint-action@master
        with:
          title-regex: '^\[[A-Z]{1}[A-Z0-9]{1,9}\-\d+\]\ [^\ ].*$'
          error-message: 'Add Jira ID to your title'
